# docker-compose.yml
version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superstrongpassword
      MYSQL_DATABASE: winter
      MYSQL_USER: winter
      MYSQL_PASSWORD: winter
    
  winter:
    depends_on:
      - db
    image: dragontek/wintercms:latest
    volumes:
      - winter_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      APP_DEBUG: 'false'
      DB_HOST: db
      DB_DATABASE: winter
      DB_USERNAME: winter
      DB_PASSWORD: winter
volumes:
  db_data: {}
  winter_data: {}
